### ISSUE TITLE
Allow specifying multiple statuses

### ISSUE THREAD

**Issue by chx** [amritghimire/jira-terminal#6]
When listing my issues, it'd be helpful to be able to filter on "New Request,In Review,To Do" or some other similar syntax.

Note I was able to do `jira-terminal list -j 'assignee = "chx@example.com" AND status != "Closed"'` so this issue is low priority, I guess.

**Comment by chx** [comment]
Thanks _so much_ for the rapid progress.

After the commit I tried more things and found `jira-terminal list -S 'In Progress' 'To Do' 'New Request'` to work for multiple . I am not sure whether this is intentional or some JQL weirdness but ... it's amazing! :)

**Comment by jetm** [comment]
@amritghimire Is it possible to pass a negation to the status name to list the other issues? 
There is case where it would be shorter to write something like this: `jira-terminal list -S "~Closed"` to list all issues are not closed, instead of writing all the possible statuses. I know is possible to write a query, but it will be nice to supported it. Thanks!
